Jeff al/uce 115 asignar permisos
josed1608/CoopeTicoBackEnd pull request #12
Opened 2019-04-15 05:49 UTC by jeff-al

Finalizo la lógica para asignar asignar permisos, ver permisos generales y ver permisos por grupo.

2019-04-15 23:45 UTC, josed1608 commented on src/main/java/com/coopetico/coopeticobackend/controladores/PermisosGrupoControlador.java
> +            int permisoID = pgEntrante.getPkIdPermisos();
Mae creo que no ocupa agregarle las entidades desde acá. Con solo el PK el mae crea las asociaciones solo, así se ahorra los dos SELECTS que hace por debajo.

2019-04-15 23:46 UTC, josed1608 commented
Mae nada más agrege los comentarios a los controladores en los métodos que falten y fíjese en el comentario que le dejé en el Controlador de PermisosGrupos

2019-04-15 23:49 UTC, josed1608 requested changes
Comentarios de arriba

2019-04-16 05:44 UTC, jeff-al commented on src/main/java/com/coopetico/coopeticobackend/controladores/PermisosGrupoControlador.java
> +            int permisoID = pgEntrante.getPkIdPermisos();
Mae sin hacer eso no funka, yo he pensado que puede ser porque el repositorio es de esa entidad y no de la entidad de PK.

2019-04-16 05:45 UTC, jeff-al commented on src/main/java/com/coopetico/coopeticobackend/controladores/PermisosGrupoControlador.java
> +            int permisoID = pgEntrante.getPkIdPermisos();
Y ya están lo comentarios de los métodos 💃

2019-04-18 04:36 UTC, merged