Jorge0117/cobe 194 borrado logico taxi
josed1608/CoopeTicoBackEnd pull request #29
Opened 2019-05-13 01:36 UTC by Jorge0117

Probar con la rama de borrado lógico del frontend

2019-05-15 16:30 UTC, geraldvindas requested changes
Le dejé algunos comentarios, cualquier duda me avisa.

2019-05-15 16:30 UTC, geraldvindas commented on src/main/java/com/coopetico/coopeticobackend/controladores/TaxisControlador.java
> +    public TaxisControlador(TaxisServicio taxisServicio){
Falta documentación del constructor, otra cosa cuando usa la notación de spring de @Autowired, lo que hace es inyección de dependencias, esto  se auto instancia el objeto, entonces no necesita recibirlo en el constructor.

Quedaría como 
public TaxisControlador() {}

2019-05-15 16:30 UTC, geraldvindas commented on src/main/java/com/coopetico/coopeticobackend/controladores/TaxistasControlador.java
> +    private final TaxistasServicio taxistaServicio;
Esto debería utilizar la notación @Autowired.

2019-05-15 16:30 UTC, geraldvindas commented on src/main/java/com/coopetico/coopeticobackend/controladores/TaxistasControlador.java
> +    private final TokensRecuperacionContrasenaServicioImpl tokensServicio;
Esto debería utilizar la notación @Autowired, esto se usa para que spring cree un bean solamente.

2019-05-15 16:30 UTC, geraldvindas commented on src/main/java/com/coopetico/coopeticobackend/controladores/TaxistasControlador.java
> +    private final EmailServiceImpl correoServicio;
Esto debería utilizar la notación @Autowired.

2019-05-15 16:30 UTC, geraldvindas commented on src/main/java/com/coopetico/coopeticobackend/controladores/TaxistasControlador.java
> +    private TaxistasControlador(TaxistasServicio taxistaServicio, TokensRecuperacionContrasenaServicioImpl tokensServicio, EmailServiceImpl correoServicio){
Si utiliza la notación @Autowired, este constuctor lo único que debería tener es 
constructor() {
 this.utilidadesControlador = new UtilidadesControlador();
}

2019-05-15 16:30 UTC, geraldvindas commented on src/main/java/com/coopetico/coopeticobackend/entidades/TaxistaEntidadTemporal.java
> +    public TaxistaEntidadTemporal(TaxistaEntidad taxista){
Documentación al constructor

2019-05-16 01:13 UTC, Jorge0117 commented on src/main/java/com/coopetico/coopeticobackend/entidades/TaxistaEntidadTemporal.java
> +    public TaxistaEntidadTemporal(TaxistaEntidad taxista){
Ese no lo hice yo y la verdad no entiendo muy bien para que se usa. Mejor que lo comente el que lo hizo

2019-05-16 01:13 UTC, geraldvindas approved these changes

2019-05-16 01:19 UTC, merged